apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
        - name: go-web
          image: bwei/go-web:ce912916bf6735ad2375e97edc011067bbf1a5a0
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.1.7-debug
          imagePullPolicy: Always
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/conf
      volumes:
        - name: config
          configMap:
            name: app-fluent-bit-cm
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: go-web
spec:
  selector:
    app: go-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-fluent-bit-cm
data:
  custom_parsers.conf: |
    
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1 
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path  /var/log/flb-storage
        storage.sync  full
        storage.metrics on
        storage.delete_irrecoverable_chunks on
    
    [INPUT]
        Name              tail
        Tag               app.*
        Path              /var/log/app/*.log
        DB                /var/log/app.db
        Mem_Buf_Limit     100MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
        storage.type      filesystem
        storage.pause_on_chunks_overlimit on
    
    [OUTPUT]
        Name              stdout
        Match             app.*
  
